
name: train_plksr
model_type: otf
scale: 4
use_amp: false
bfloat16: false
fast_matmul: false
compile: false
#manual_seed: 1024

gt_size: 192
queue_size: 160

datasets:
  train:
    type: otf
    dataroot_gt: 'datasets/gt/'
    #meta_info: 'datasets/meta_info.txt'
    io_backend:
      type: disk

    batch_size: 8
    accumulate: 1
    dataset_enlarge_ratio: 1

    use_hflip: true
    use_rot: true
    augmentation: ['none', 'mixup', 'cutmix', 'resizemix', 'cutblur']
    aug_prob: [0.2, 0.3, 0.2, 0.5, 0.7]

    blur_kernel_size: 7
    kernel_list: ["iso", "aniso", "generalized_iso", "generalized_aniso", "plateau_iso", "plateau_aniso"]
    kernel_prob: [0.45, 0.25, 0.12, 0.03, 0.12, 0.03]
    sinc_prob: 0.1
    blur_sigma: [0.2, 3]
    betag_range: [0.5, 4]
    betap_range: [1, 2]

    blur_kernel_size2: 9
    kernel_list2: ["iso", "aniso", "generalized_iso", "generalized_aniso", "plateau_iso", "plateau_aniso"]
    kernel_prob2: [0.45, 0.25, 0.12, 0.03, 0.12, 0.03]
    sinc_prob2: 0.1
    blur_sigma2: [0.2, 1.5]
    betag_range2: [0.5, 4]
    betap_range2: [1, 2]

    final_sinc_prob: 0.8

#  val:
#    name: val_1
#    type: paired
#    dataroot_gt: 'datasets/val/gt/'
#    dataroot_lq: 'datasets/val/lq/'
#    io_backend:
#      type: disk

#val:
#  val_freq: 1000
#  save_img: true
#  tile: -1 # 200
#  metrics:
#    psnr:
#      type: calculate_psnr
#    ssim:
#      type: calculate_ssim
#    dists:
#      type: calculate_dists
#      better: lower

resize_prob: [0.3, 0.4, 0.3] # up, down, keep
resize_range: [0.5, 1.5]
gaussian_noise_prob: 0.2
noise_range: [0, 2]
poisson_scale_range: [0.05, 0.25]
gray_noise_prob: 0.1
jpeg_range: [40, 95]

# the second degradation process
second_blur_prob: 0.4
resize_prob2: [0.3, 0.4, 0.3] # up, down, keep
resize_range2: [0.3, 1.5]
gaussian_noise_prob2: 0.2
noise_range2: [0, 2]
poisson_scale_range2: [0.05, 0.1]
gray_noise_prob2: 0.1
jpeg_range2: [35, 95]

path:
  #pretrain_network_g: 'experiments/pretrain.pth'
  resume_state: ~
  #strict_load_g: false # do not uncomment, read docs

network_g:
  type: plksr
  #type: plksr_tiny

network_d:
  type: a2fpnpp

train:
  #eco: true
  #eco_init: 15000

  ema: 0.999
  #sam: "fsam"
  #sam_init: 1000
  total_iter: 1000000

  optim_g:
    type: adan_sf
    lr: !!float 5e-4
    betas: [0.98, 0.92, 0.987]
    weight_decay: 0.02
    schedule_free: true
    #warmup_steps: 1600

  optim_d:
    type: adan_sf
    lr: !!float 8e-4
    betas: [0.98, 0.92, 0.995]
    weight_decay: 0.02
    schedule_free: true
    #warmup_steps: 500

  # losses
  #wavelet_guided: true
  #wavelet_init: 80000
  mssim_opt:
    type: mssim
    loss_weight: 1.0
  perceptual_opt:
    type: PerceptualLoss
    layer_weights:
      'conv1_2': 0.1
      'conv2_2': 0.1
      'conv3_4': 1
      'conv4_4': 1
      'conv5_4': 1
    perceptual_weight: 1.0
    criterion: huber
    #patchloss: true
    #ipk: true
    #perceptual_patch_weight: 1.0
  gan_opt:
    type: GANLoss
    gan_type: vanilla
    loss_weight: 0.3
  #dists_opt:
  #  type: dists
  #  loss_weight: 0.5
  #ldl_opt:
  #  type: HuberLoss
  #  loss_weight: 1.0
  #ff_opt:
  #  type: focalfrequencyloss
  #  loss_weight: 0.5
  #gw_opt:
  #  type: gw_loss
  #  loss_weight: 1.0
  #  criterion: chc

  #match_lq: true
  color_opt:
    type: colorloss
    loss_weight: 1.0
    criterion: huber
  luma_opt:
    type: lumaloss
    loss_weight: 1.0
    criterion: huber

logger:
  print_freq: 100
  save_checkpoint_freq: 1000
  use_tb_logger: true
  #save_tb_img: true
